### PR TITLE
Always run add-git-section script on un-deprecated files

### LINKED ISSUE #463: Fix git commit script
Time Converting Exercise has the wrong git message and the script does not fix it.

```
$ git add .
$ git commit -m "finish itinerary exercise"
```

### PR DESCRIPTION
**Pull request by pascalwengerter**
Supersedes #468
Fixes #463

### CODE REVIEW

File: utils/lib/mix/tasks/add_git_section.ex [hunk 1]
```diff
@@ -49,13 +49,22 @@ defmodule Mix.Tasks.Bc.AddGitSection do
     """
   end
 
-  defp commit_snippet_present?(path) do
-    File.read!(path) |> String.contains?("## Commit Your Progress")
+  defp depricated_file?(path) do
+    String.contains?(path, ["DEPRECATED", "DEPRICATED"])
```
Comment (BrooklinJazz) [inline utils/lib/mix/tasks/add_git_section.ex:53]: I think we just need to change the DEPRICATED files to DEPRECATED files and the remove DEPRICATED from this list.

**Review by BrooklinJazz — CHANGES_REQUESTED** [review]

**Review by BrooklinJazz — APPROVED** [review]
Looks great!
